version: '3.8'
services:
  # Django app
  backend_cart:
    container_name: boomslag_ms_cart
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8002"
    volumes:
      - .:/app
    ports:
      - 8002:8002
  # Event Queue Kafka
  cart_queue:
    build: .
    command: >
      sh -c "python consumer.py"