# Generated by Django 3.2.16 on 2023-02-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='material',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
