# Generated by Django 3.2.16 on 2023-03-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20230204_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='referrer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
